@startuml Business Logic 
title Class Diagram - Inkasso Business Logic 

class Debt {
  +Id:int
}

class Person
{
  +Id:int
  +Name:string
}
class Contract
{
  +Id:int
  +Name:string
  +Intrest:decmal
  +Fee:decimal
}
class Transaction
{
  +Id:int
  +Date:datetime
  +Amount: decimal
  
}


Person *-right-"*"  Debt
Contract  *-left- "*" Debt
Debt *-- Transaction



class Contracts
{
  +GetContracts():List<Contact>
  +GetContract(Id:int):Contact
  +CreateContract(contract:Contract)
  +SeedContracts(count:int,companies:string)
}
class Persons
{
  +GetPersons():List<Person>
  +GetPerson(Id:int):Person
  +CreatePerson(person:Person, contract:Contract, amount:decimal)
  +UpdatePerson(person:Person)
  +SeedPersons(count:int,names:string)
}
class Debts
{
  +GetDebs():List<Debt>
  +GetDebs(person:Person):List<Debt>
  +GetDebt(Id:int):Debt
  +CreateDebt(person:Person,contract:Contract,Amount:int)
}
class Transactions
{
  +GetTransactions(Debt:debt):List<Transactions>
  +GetTransaction(Id:int):Transaction
  +CreateTransaction(transaction:Transaction)
  +SeedTransactions()
}

Persons -right-> Person
Contracts -left->Contract
Debts -down->Debt
Debts .down.>Person
Transactions -left->Transaction
Transactions .up.>Debt

enum TransactionTypes
{
SALDO
PAY
INTREST
FEE
}

Transactions .right.> TransactionTypes
@enduml